### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [MiniclipPortugal/RakNet#6]
@g-andrade: would it be too cumbersome to have potentially existing code test under Travis CI? Or is this request absurd and can be closed straight away?

**Comment by g-andrade** [comment]
If you're OK with labeling this issue as "utopic improvement" (assuming custom labels are allowed), I'd be OK with keeping it open :-).

Very unlikely to happen, but not technically impossible, although perhaps pointless if we start using [SLikeNet](https://github.com/SLikeSoft/SLikeNet) instead, RakNet's maintained successor.
